# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 208e3583ecc5da2c51d882fda7539ed61b653f0025de9ca42f64a70287c0a774f695ceffb5e0608e5a38ef3daf63be8d765d4c336950d448bf25f57c3ac7e13a

test:
  secret_key_base: a61461244497596a1f12c541d44e040b891381b17141509ccc1c180c86f88c2bca8da49ef1d8631fe3e34f851918362c2fc660548934f143cace345dc191ab19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
